[package]
name = "ruma-identifiers-validation"
description = "Validation logic for ruma-common and ruma-macros"
homepage = "https://www.ruma.io/"
repository = "https://github.com/ruma/ruma"
license = "MIT"
version = "0.9.2"
edition = "2021"
rust-version = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[features]
# Allow IDs to exceed 255 bytes.
compat-arbitrary-length-ids = []

# Don't validate the version part in `key_id::validate`.
compat-key-id = []

# Allow some user IDs that are invalid even with the specified historical
# user ID scheme.
compat-user-id = []
unstable-msc3917 = []

[dependencies]
js_int = { workspace = true }
thiserror = { workspace = true }
